<?php

return [
    'recipient' => env('ADMIN_EMAIL', 'info@leget.ru'),
    // Optional server-only override, useful on staging. Never accepted from a form.
    'recipient_override' => env('FORM_RECIPIENT_OVERRIDE'),
    'attachment_disk' => env('FORM_ATTACHMENT_DISK', 'yandex'),
    'max_attempts' => 8,
    'titles' => [
        'platform-footer-subscription' => 'Будь в курсе событий',
        'promo1-footer-subscription' => 'Подписка на новости',
        'promo1-contact' => 'Контакты', 'promo2-contact' => 'Контакты',
        'promo3-contact' => 'Скидка 10%', 'promo3-vacancy' => 'Напишите нам',
        'promo1-vacancy' => 'Напишите нам', 'promo2-careers' => 'Открытое резюме',
        'promo2-designers' => 'Заявка на партнёрство', 'promo1-partnership' => 'Партнёрство',
        'promo1-warranty' => 'Гарантийное обращение', 'promo1-installment' => 'Заявка на рассрочку',
        'platform-contact' => 'Заявка на интеграцию',
        'promo1-appliance-selection' => 'Подбор техники',
        'promo1-plumbing-selection' => 'Подбор сантехники',
    ],
    'types' => [
        'consultation' => 'Консультация',
        'design-project' => 'Дизайн-проект',
        'furniture-project' => 'Проектирование мебели',
        'assembly' => 'Сборка и монтаж',
        'measurement' => 'Заказ замера',
        'countertop-estimate' => 'Просчёт столешницы',
        'appliance-selection' => 'Подбор техники',
        'plumbing-selection' => 'Подбор сантехники',
        'installment' => 'Рассрочка',
        'partnership' => 'Сотрудничество',
        'promo' => 'Промокод',
        'vacancy' => 'Отклик на вакансию',
        'careers' => 'Отклик на вакансию',
        'warranty' => 'Гарантийное обращение',
        'contact' => 'Обратная связь',
        'subscription' => 'Подписка',
        'partner-application' => 'Заявка партнёра платформы',
    ],
    'conversion_types' => ['consultation', 'design-project', 'furniture-project', 'assembly', 'measurement', 'countertop-estimate', 'appliance-selection', 'plumbing-selection', 'installment', 'partnership', 'promo', 'contact'],
];
